### PR TITLE
699 - create one liner to compile/run the game

### PR DESCRIPTION
**Pull request by alexis-turpin**
create a curl pipe bash one liner to compile and run the game
and edit the README.md accordingly

### CODE REVIEW

**Comment by alexis-turpin** [comment]
Sorry for the early PR. I didn't tested my changes before submitting it.
Now everything should work.

You can try it by yourself with : 
`curl -s https://raw.githubusercontent.com/alexis-turpin/Memoris/master/install.sh | sudo bash`

**Comment by jean553** [comment]
Thanks for your help. Actually, it seems the cd command of the script is not working properly.
```
[sudo] password for jean: 
bash: line 1: add-apt-repository: command not found
E: Invalid operation update
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package git
bash: line 4: add-apt-repository: command not found
bash: line 5: $'\r': command not found
Cloning into 'Memoris'...
remote: Counting objects: 8632, done.
remote: Compressing objects: 100% (170/170), done.
remote: Total 8632 (delta 93), reused 0 (delta 0), pack-reused 8459
Receiving objects: 100% (8632/8632), 38.06 MiB | 133.00 KiB/s, done.
Resolving deltas: 100% (6280/6280), done.
Checking connectivity... done.
: No such file or directory
: No such file or directory
" does not exist.source directory "/tmp/..
Specify --help for usage, or press the help button on the CMake GUI.
bash: line 10: $'make\r': command not found
: No such file or directorys
```

**Comment by alexis-turpin** [comment]
Alright, finally found some time to isolated the problem.
At the end it was an obvious mistake: format. I typed the script using Windows.
I can simply correct the problem with:
`sed -i 's/\r//' install.sh`

But the project still doesn't compile. Find the detailed error here:
```
Cloning into 'Memoris'...
remote: Counting objects: 9677, done.
remote: Total 9677 (delta 0), reused 0 (delta 0), pack-reused 9677
Receiving objects: 100% (9677/9677), 38.08 MiB | 1.19 MiB/s, done.
Resolving deltas: 100% (7114/7114), done.
Checking connectivity... done.
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is Clang 3.5.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-3.5
-- Check for working CXX compiler: /usr/bin/clang++-3.5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SFML 2.4.0 in /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/test/Memoris/build
Scanning dependencies of target Memoris
[  1%] Building CXX object CMakeFiles/Memoris.dir/src/main.cpp.o
[  2%] Building CXX object CMakeFiles/Memoris.dir/src/AbstractMenuController.cpp.o
[  4%] Building CXX object CMakeFiles/Memoris.dir/src/AbstractMirrorAnimation.cpp.o
[  5%] Building CXX object CMakeFiles/Memoris.dir/src/AnimatedBackground.cpp.o
[  7%] Building CXX object CMakeFiles/Memoris.dir/src/Button.cpp.o
[  8%] Building CXX object CMakeFiles/Memoris.dir/src/Cell.cpp.o
[  9%] Building CXX object CMakeFiles/Memoris.dir/src/CellsSelector.cpp.o
[ 11%] Building CXX object CMakeFiles/Memoris.dir/src/CellsTexturesManager.cpp.o
[ 12%] Building CXX object CMakeFiles/Memoris.dir/src/ColorsManager.cpp.o
[ 14%] Building CXX object CMakeFiles/Memoris.dir/src/Context.cpp.o
[ 15%] Building CXX object CMakeFiles/Memoris.dir/src/Controller.cpp.o
[ 16%] Building CXX object CMakeFiles/Memoris.dir/src/Cursor.cpp.o
[ 18%] Building CXX object CMakeFiles/Memoris.dir/src/DiagonalAnimation.cpp.o
[ 19%] Building CXX object CMakeFiles/Memoris.dir/src/Dialog.cpp.o
/tmp/test/Memoris/src/Dialog.cpp:171:17: error: 'setColor' is deprecated [-Werror,-Wdeprecated-declarations]
    impl->title.setColor(context.getColorsManager().getColorWhite());
                ^
/usr/include/SFML/Graphics/Text.hpp:177:26: note: 'setColor' has been explicitly marked deprecated here
    SFML_DEPRECATED void setColor(const Color& color);
                         ^
1 error generated.
CMakeFiles/Memoris.dir/build.make:374: recipe for target 'CMakeFiles/Memoris.dir/src/Dialog.cpp.o' failed
make[2]: *** [CMakeFiles/Memoris.dir/src/Dialog.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Memoris.dir/all' failed
make[1]: *** [CMakeFiles/Memoris.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

On a fresh install of Ubuntu 16.10, trying on a 14.04 LTS by the end of the week.

**Comment by alexis-turpin** [comment]
Made it work with 14.04. Double test it on your side, but I think you could merge now.

It might be a good idea to make it work for 16.04 in the future I think. Should I open an issue for that ?

**Comment by alexis-turpin** [comment]
Any problem with this PR ?

**Comment by jean553** [comment]
Hello Alexis,

Thanks for your participation and sorry for the delay in getting back to you. Yes, we can merge your PR and I also created an issue for Ubuntu 16.04 compatibility as you suggested.

Thanks!
